import { vi } from 'vitest';

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const fixtureDir = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../fixtures/pay-page',
);

/**
 * The real pay page, as rendered by the gateway.
 *
 * Generated by PayPageContractTest rather than written here: the previous
 * hand-maintained copy had drifted, missing the amount, the "open in wallet"
 * link and the status element's initial text, so these tests were exercising
 * markup no customer ever sees.
 *
 * Regenerate with:
 *   BLINK_UPDATE_FIXTURES=1 composer test:integration -- --filter PayPageContract
 */
export const PAY_PAGE_HTML = readFileSync(join(fixtureDir, 'rendered.html'), 'utf8');

/** The real payload the page ships, with per-run values already normalised. */
const FIXTURE_PAYLOAD = JSON.parse(
  readFileSync(join(fixtureDir, 'payload.json'), 'utf8'),
);

export function defaultConfig(overrides = {}) {
  return {
    // Structural clone so a test mutating its config cannot affect the next.
    ...structuredClone(FIXTURE_PAYLOAD),
    // The fixture's deadline is a fixed timestamp; tests want one relative to
    // the frozen clock they set.
    deadline: Math.floor(Date.now() / 1000) + 3600,
    ...overrides,
  };
}

const registered = [];

/**
 * Records the listeners pay.js attaches so they can be removed again.
 *
 * jsdom keeps one document for the whole test file, so without this every
 * previously loaded copy of the script keeps polling and the request counts
 * from different tests bleed into each other.
 */
function trackListeners() {
  for (const target of [document, window]) {
    const original = target.addEventListener.bind(target);
    target.addEventListener = (type, listener, options) => {
      registered.push({ target, type, listener, options });
      original(type, listener, options);
    };
    registered.push({ target, restore: original });
  }
}

export function cleanupPayScript() {
  for (const entry of registered.splice(0)) {
    if (entry.restore) {
      entry.target.addEventListener = entry.restore;
      continue;
    }
    entry.target.removeEventListener(entry.type, entry.listener, entry.options);
  }
}

/**
 * Loads pay.js the way the browser would.
 *
 * The global has to exist before the module is imported, because the script
 * returns immediately when it is missing. Importing (rather than eval'ing the
 * file contents) is what lets the coverage instrumenter see the file at all --
 * a readFileSync + new Function approach runs fine and reports zero coverage,
 * which would make the threshold meaningless.
 */
export async function loadPayScript(config = defaultConfig(), html = PAY_PAGE_HTML) {
  cleanupPayScript();
  document.body.innerHTML = html;
  trackListeners();

  if (config !== null) {
    globalThis.BlinkPay = config;
  } else {
    delete globalThis.BlinkPay;
  }

  vi.resetModules();
  // No cache-busting query here: a unique module id per import makes the
  // coverage instrumenter treat each one as a separate file and split the
  // attribution. resetModules() alone is enough to re-execute the script.
  await import('../../../assets/js/frontend/pay.js');

  document.dispatchEvent(new Event('DOMContentLoaded'));
}

export function jsonResponse(data, status = 200) {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: () => Promise.resolve(data),
  };
}

export function statusText() {
  return document.getElementById('blink-pay-status').textContent;
}
